/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Ashada
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        Pmenu = new javax.swing.JPanel();
        navbarDashboard = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        navbarData = new javax.swing.JPanel();
        dataLabel = new javax.swing.JLabel();
        navbarComing = new javax.swing.JPanel();
        comingLabel = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        mainDashboard = new javax.swing.JPanel();
        mainData = new javax.swing.JPanel();
        mainComing = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Inventaris Aset");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        navbar.setBackground(new java.awt.Color(255, 255, 255));

        Pmenu.setLayout(new javax.swing.BoxLayout(Pmenu, javax.swing.BoxLayout.Y_AXIS));

        navbarDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbarDashboardMouseClicked(evt);
            }
        });

        dashboardLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dashboardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N
        dashboardLabel.setText("Dashboard");

        javax.swing.GroupLayout navbarDashboardLayout = new javax.swing.GroupLayout(navbarDashboard);
        navbarDashboard.setLayout(navbarDashboardLayout);
        navbarDashboardLayout.setHorizontalGroup(
            navbarDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarDashboardLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(dashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navbarDashboardLayout.setVerticalGroup(
            navbarDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Pmenu.add(navbarDashboard);

        navbarData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbarDataMouseClicked(evt);
            }
        });

        dataLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dataLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/data.png"))); // NOI18N
        dataLabel.setText("Data Aset");

        javax.swing.GroupLayout navbarDataLayout = new javax.swing.GroupLayout(navbarData);
        navbarData.setLayout(navbarDataLayout);
        navbarDataLayout.setHorizontalGroup(
            navbarDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarDataLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navbarDataLayout.setVerticalGroup(
            navbarDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Pmenu.add(navbarData);

        navbarComing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbarComingMouseClicked(evt);
            }
        });

        comingLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        comingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        comingLabel.setText("Coming Soon");

        javax.swing.GroupLayout navbarComingLayout = new javax.swing.GroupLayout(navbarComing);
        navbarComing.setLayout(navbarComingLayout);
        navbarComingLayout.setHorizontalGroup(
            navbarComingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarComingLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(comingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navbarComingLayout.setVerticalGroup(
            navbarComingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Pmenu.add(navbarComing);

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        user.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("Administrator");

        logout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        logout.setText("Logout");

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navbarLayout.createSequentialGroup()
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(navbar);

        mainPanel.setLayout(new java.awt.CardLayout());

        mainDashboard.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout mainDashboardLayout = new javax.swing.GroupLayout(mainDashboard);
        mainDashboard.setLayout(mainDashboardLayout);
        mainDashboardLayout.setHorizontalGroup(
            mainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        mainDashboardLayout.setVerticalGroup(
            mainDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        mainPanel.add(mainDashboard, "dashboard");

        mainData.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout mainDataLayout = new javax.swing.GroupLayout(mainData);
        mainData.setLayout(mainDataLayout);
        mainDataLayout.setHorizontalGroup(
            mainDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        mainDataLayout.setVerticalGroup(
            mainDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        mainPanel.add(mainData, "data");

        mainComing.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout mainComingLayout = new javax.swing.GroupLayout(mainComing);
        mainComing.setLayout(mainComingLayout);
        mainComingLayout.setHorizontalGroup(
            mainComingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        mainComingLayout.setVerticalGroup(
            mainComingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        mainPanel.add(mainComing, "coming");

        getContentPane().add(mainPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void navbarDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbarDashboardMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(mainPanel.getLayout());
        c1.show(mainPanel, "dashboard");
    }//GEN-LAST:event_navbarDashboardMouseClicked

    private void navbarDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbarDataMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(mainPanel.getLayout());
        c1.show(mainPanel, "data");
    }//GEN-LAST:event_navbarDataMouseClicked

    private void navbarComingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbarComingMouseClicked
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(mainPanel.getLayout());
        c1.show(mainPanel, "coming");
    }//GEN-LAST:event_navbarComingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pmenu;
    private javax.swing.JLabel comingLabel;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel img;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel mainComing;
    private javax.swing.JPanel mainDashboard;
    private javax.swing.JPanel mainData;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel navbarComing;
    private javax.swing.JPanel navbarDashboard;
    private javax.swing.JPanel navbarData;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
